version: '3.4'

services:
  apiwithsql:
    image: ${DOCKER_REGISTRY}apiwithsql
    ports:
     - "8000:80"
    build:
      context: .
      dockerfile: APIWithSql/Dockerfile
    depends_on:
      - db 
   
  db:
   image: microsoft/mssql-server-linux:2017-latest
   ports: 
    - "1433:1433"
   environment:
    SA_PASSWORD: "PassW0rd"
    ACCEPT_EULA: "Y"
