### The following is the "svc.yml" file used in the module
apiVersion: v1
kind: Service
metadata:
  name: hello2-svc
  labels:
    app: hello-world
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 32319
    protocol: TCP
  selector:
    app: hello-world

