#Ubuntu based hello World container
FROM ubuntu:15.04
MAINTAINER hersh_b@abc.com
RUN apt-get update
RUN apt-get install -y apache2
RUN apt-get install -y vim
RUN apt-get install -y golang
CMD ["echo", "Hello World"]

